// Vulkan samples
// The MIT License (MIT)
// Copyright (c) 2016 Alexey Gruzdev

#version 450

layout(local_size_x = 1, local_size_y = 1) in;

layout(set = 0, binding = 0) uniform usampler2D inImage;
layout(set = 0, binding = 1, rgba32f) uniform image2D outImage;


void main() {
    const vec2 TC = vec2(gl_WorkGroupID.xy) / vec2(gl_NumWorkGroups.xy);
    const uvec3 rgb = texture(inImage, vec2(TC.x, 1.0 - TC.y)).rgb;
    imageStore(outImage, ivec2(gl_WorkGroupID.xy), vec4(rgb / 255.0, 1.0));
}
